[tool.ruff]
src = ['src', 'tests']
ignore = [
  'B019',
  'D100',
  'D103',
]
line-length = 88
select = [
    'A',
    'ARG',
    'B',
    'B9',
    'BLE',
    'C',
    'C4',
    'E',
    'F',
    'I',
    'N',
    'PIE',
    'PT',
    'PTH',
    'Q',
    'RET',
    'RUF',
    'S',
    'SIM',
    'SLF',
    'T10',
    'TCH',
    'UP',
    'W',
]

[tool.ruff.per-file-ignores]
"__init__.py" = ['F401']
"test_*.py" = [
    'S',
    'D212',
    'D415',
    'D205',
    'D104',
]

[tool.ruff.mccabe]
max-complexity = 10

[tool.ruff.pydocstyle]
convention = 'google'

